------------
-- Generated by BetterVim
------------
local generated_plugins_list = {
  { "justinmk/vim-sneak" },
  { "rhysd/clever-f.vim" },
  { "iamcco/markdown-preview.nvim" },
  { "majutsushi/tagbar" },
  { "tpope/vim-fugitive" },
  { "thaerkh/vim-workspace" },
  { "tpope/vim-rsi" },
}

return {
  theme = {
    name = "palenight",
  },
  mappings = {
    custom = {
      ["<c-e>"] = { "<End>" },
      ["<c-a>"] = { "<Home>" }
    }
  },
  lsps = {
    ruby_lsp = {},
  },
  formatters = {
    erb_format = {},
    erb_lint = {},
    htmlbeautifier = {},
    rubocop = {},
  },
  plugins = generated_plugins_list,
  flags = {
    format_on_save = false,
  },
  hooks = {
    after_setup = function()
      vim.cmd [[
        let g:workspace_session_directory = $HOME . '/.vim/sessions/'
        let g:workspace_autocreate = 1
        let g:sneak#label = 1
        nmap <F3> :TagbarToggle<CR>
        set relativenumber
        set wrap linebreak
      ]]
    end,
  }
}
